// config/seo.ts — SEO configuration for OnCall Home Repairs Hinckley
// Generated by local-seo-site skill. Single source of truth for all pages.

export const seoConfig = {
  // Business Identity
  business: {
    name: "OnCallHomeRepairs",
    legalName: "OnCall Home Repairs",
    industry: "Plumbing",
    description:
      "Emergency plumber matching network connecting customers with vetted, local plumbers 24/7 in Hinckley and Leicestershire",
    foundedYear: null as number | null,
    phone: "0333 240 8428",
    phoneTel: "tel:03332408428",
    email: "info@oncallhomerepairs.co.uk",
    url: "https://oncallhomerepairs.co.uk",
  },

  // Location
  location: {
    address: "27 Wendover Drive",
    city: "Hinckley",
    county: "Leicestershire",
    postcode: "LE10 1UQ",
    country: "United Kingdom",
    countryCode: "GB",
    geo: { lat: 52.5414, lng: -1.3728 },
  },

  // Google Business Profile
  gbp: {
    primaryCategory: "Plumber",
    secondaryCategories: [
      "Emergency Plumber",
      "Plumbing Contractor",
      "Drain Cleaning Service",
      "Boiler Repair Service",
    ],
    placeId: "ChIJLf8fOUOsKkgRNlchm4A2IfU",
    mapsUrl: "https://maps.google.com/?cid=17645219937279493942",
    mapEmbed:
      "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d38811.16617766433!2d-1.3640895!3d52.5569895!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x632aac43791fff2d%3A0xf52136809b215736!2sOn%20Call%20Home%20Repairs!5e0!3m2!1sen!2suk!4v1771588492399!5m2!1sen!2suk",
  } as {
    primaryCategory: string;
    secondaryCategories: string[];
    placeId?: string;
    mapsUrl?: string;
    mapEmbed?: string;
  },

  // Services (drives page generation)
  services: {
    categories: [
      {
        name: "Emergency Plumbing",
        slug: "emergency-plumbing",
        description:
          "24/7 emergency plumbing in Hinckley — burst pipes, leaks, floods, and urgent repairs",
        services: [
          {
            name: "Emergency Plumber",
            slug: "emergency-plumber",
            description:
              "24-hour emergency plumber in Hinckley. Fast response for burst pipes, leaks, and flooding.",
            keywords: ["emergency plumber Hinckley", "24 hour plumber Hinckley"],
            isCoreService: true,
          },
          {
            name: "Burst Pipe Repair",
            slug: "burst-pipe-repair",
            description:
              "Fast burst pipe repair in Hinckley. Emergency call-out available 24/7.",
            keywords: ["burst pipe repair Hinckley", "burst pipe Hinckley"],
            isCoreService: true,
          },
          {
            name: "Leak Detection and Repair",
            slug: "leak-detection-repair",
            description:
              "Professional leak detection and repair in Hinckley. Find and fix hidden leaks fast.",
            keywords: ["leak detection Hinckley", "water leak repair Hinckley"],
            isCoreService: true,
          },
          {
            name: "Frozen Pipe Repair",
            slug: "frozen-pipe-repair",
            description:
              "Frozen pipe thawing and repair in Hinckley. Prevent burst pipes this winter.",
            keywords: ["frozen pipe repair Hinckley", "frozen pipes Hinckley"],
            isCoreService: false,
          },
          {
            name: "Flood Response",
            slug: "flood-response",
            description:
              "Emergency flood response plumber in Hinckley. Rapid water damage control.",
            keywords: [
              "flood response plumber Hinckley",
              "emergency flooding Hinckley",
            ],
            isCoreService: false,
          },
          {
            name: "Stopcock Repair",
            slug: "stopcock-repair",
            description:
              "Stopcock repair and replacement in Hinckley. Regain control of your water supply.",
            keywords: ["stopcock repair Hinckley", "stopcock replacement Hinckley"],
            isCoreService: false,
          },
          {
            name: "Overflow Repair",
            slug: "overflow-repair",
            description:
              "Overflow pipe repair in Hinckley. Stop water leaks from tanks and cisterns.",
            keywords: ["overflow repair Hinckley", "overflow pipe Hinckley"],
            isCoreService: false,
          },
        ],
      },
      {
        name: "Boiler & Heating",
        slug: "boiler-heating",
        description:
          "Boiler repair, installation, and central heating services in Hinckley, Leicestershire",
        services: [
          {
            name: "Boiler Repair",
            slug: "boiler-repair",
            description:
              "Expert boiler repair in Hinckley. Gas Safe registered engineers available 24/7.",
            keywords: ["boiler repair Hinckley", "boiler breakdown Hinckley"],
            isCoreService: true,
          },
          {
            name: "Boiler Installation",
            slug: "boiler-installation",
            description:
              "New boiler installation in Hinckley. Gas Safe registered, competitive pricing.",
            keywords: [
              "boiler installation Hinckley",
              "new boiler Hinckley",
            ],
            isCoreService: true,
          },
          {
            name: "Central Heating Repair",
            slug: "central-heating-repair",
            description:
              "Central heating repair in Hinckley. Radiators, pumps, valves, and full system diagnostics.",
            keywords: [
              "central heating repair Hinckley",
              "heating engineer Hinckley",
            ],
            isCoreService: true,
          },
          {
            name: "Boiler Servicing",
            slug: "boiler-servicing",
            description:
              "Annual boiler servicing in Hinckley. Keep your warranty valid and your boiler efficient.",
            keywords: ["boiler servicing Hinckley", "boiler service Hinckley"],
            isCoreService: false,
          },
          {
            name: "Radiator Repair and Installation",
            slug: "radiator-repair-installation",
            description:
              "Radiator repair and installation in Hinckley. Fix cold spots, leaks, and add new radiators.",
            keywords: [
              "radiator repair Hinckley",
              "radiator installation Hinckley",
            ],
            isCoreService: false,
          },
          {
            name: "Power Flushing",
            slug: "power-flushing",
            description:
              "Power flushing in Hinckley. Remove sludge and restore heating efficiency.",
            keywords: ["power flushing Hinckley", "power flush Hinckley"],
            isCoreService: false,
          },
          {
            name: "Gas Safety Checks",
            slug: "gas-safety-checks",
            description:
              "Gas safety checks in Hinckley. CP12 certificates for landlords and homeowners.",
            keywords: [
              "gas safety check Hinckley",
              "CP12 certificate Hinckley",
            ],
            isCoreService: false,
          },
          {
            name: "Water Heater Repair",
            slug: "water-heater-repair",
            description:
              "Water heater repair in Hinckley. Immersion heaters, cylinders, and unvented systems.",
            keywords: [
              "water heater repair Hinckley",
              "hot water repair Hinckley",
            ],
            isCoreService: false,
          },
        ],
      },
      {
        name: "Drain Services",
        slug: "drain-services",
        description:
          "Blocked drain clearing, CCTV surveys, and toilet repairs in Hinckley",
        services: [
          {
            name: "Blocked Drains",
            slug: "blocked-drains",
            description:
              "Blocked drain clearing in Hinckley. Fast, effective unblocking for homes and businesses.",
            keywords: ["blocked drains Hinckley", "blocked drain Hinckley"],
            isCoreService: true,
          },
          {
            name: "Drain Unblocking",
            slug: "drain-unblocking",
            description:
              "Professional drain unblocking in Hinckley. High-pressure jetting and manual rodding.",
            keywords: [
              "drain unblocking Hinckley",
              "unblock drain Hinckley",
            ],
            isCoreService: false,
          },
          {
            name: "CCTV Drain Survey",
            slug: "cctv-drain-survey",
            description:
              "CCTV drain survey in Hinckley. Camera inspection to diagnose drainage problems.",
            keywords: [
              "CCTV drain survey Hinckley",
              "drain camera Hinckley",
            ],
            isCoreService: false,
          },
          {
            name: "Toilet Repair",
            slug: "toilet-repair",
            description:
              "Toilet repair in Hinckley. Cisterns, flush mechanisms, seals, and installations.",
            keywords: ["toilet repair Hinckley", "toilet plumber Hinckley"],
            isCoreService: false,
          },
          {
            name: "Toilet Unblocking",
            slug: "toilet-unblocking",
            description:
              "Toilet unblocking in Hinckley. Fast, hygienic clearance of blocked toilets.",
            keywords: [
              "toilet unblocking Hinckley",
              "unblock toilet Hinckley",
            ],
            isCoreService: false,
          },
        ],
      },
      {
        name: "General Plumbing",
        slug: "general-plumbing",
        description:
          "Bathroom and kitchen plumbing, tap repairs, shower installation, and pipe work in Hinckley",
        services: [
          {
            name: "Bathroom Plumbing",
            slug: "bathroom-plumbing",
            description:
              "Bathroom plumbing in Hinckley. Installations, repairs, and full bathroom fit-outs.",
            keywords: [
              "bathroom plumber Hinckley",
              "bathroom plumbing Hinckley",
            ],
            isCoreService: true,
          },
          {
            name: "Tap Repair and Replacement",
            slug: "tap-repair-replacement",
            description:
              "Tap repair and replacement in Hinckley. Fix dripping taps and install new ones.",
            keywords: ["tap repair Hinckley", "tap replacement Hinckley"],
            isCoreService: false,
          },
          {
            name: "Shower Installation and Repair",
            slug: "shower-installation-repair",
            description:
              "Shower installation and repair in Hinckley. Electric, mixer, and thermostatic showers.",
            keywords: [
              "shower installation Hinckley",
              "shower repair Hinckley",
            ],
            isCoreService: false,
          },
          {
            name: "Kitchen Plumbing",
            slug: "kitchen-plumbing",
            description:
              "Kitchen plumbing in Hinckley. Sink installations, dishwasher connections, and repairs.",
            keywords: ["kitchen plumber Hinckley", "kitchen plumbing Hinckley"],
            isCoreService: false,
          },
          {
            name: "Pipe Replacement",
            slug: "pipe-replacement",
            description:
              "Pipe replacement in Hinckley. Copper, plastic, and lead pipe upgrades.",
            keywords: [
              "pipe replacement Hinckley",
              "pipe repair Hinckley",
            ],
            isCoreService: false,
          },
        ],
      },
    ],
  },

  // Service areas
  serviceAreas: [
    "Hinckley",
    "Burbage",
    "Earl Shilton",
    "Barwell",
    "Stoney Stanton",
    "Sapcote",
    "Elmesthorpe",
    "Stoke Golding",
    "Dadlington",
    "Market Bosworth",
    "Desford",
    "Ratby",
    "Groby",
    "Markfield",
  ],

  // Differentiators
  differentiators: {
    fiveStarReviews: null as number | null,
    averageResponseTime: null as string | null,
    freeEstimates: null as boolean | null,
    tripFee: null as boolean | null,
    afterHours: true,
    twentyFourSeven: true,
    twentyFourSevenDetail:
      "Day or night, weekends or bank holidays — ready to respond when you need us most",
    yearsInBusiness: null as number | null,
    guarantees: "Workmanship guarantee — if something isn't right, we come back and put it right at no extra cost",
    transparentPricing: true,
    transparentPricingDetail:
      "Clear, upfront quote before any work begins. No hidden fees or surprise charges.",
    communication: true,
    communicationDetail: "Constant communication with customers until the job is done",
    vettedNetwork: true,
    vettedNetworkDetail:
      "All plumbers in our network are qualified, Gas Safe registered, and fully insured",
    locallyOwned: null as boolean | null,
    familyOwned: null as boolean | null,
    keyDifferentiator:
      "Network of vetted emergency plumbers available 24/7 with transparent pricing and guaranteed workmanship",
  },

  // SEO Metadata defaults
  seo: {
    titleTemplate: "%s | OnCall Home Repairs",
    defaultTitle:
      "Plumber Hinckley | 24/7 Emergency Plumbing — OnCall Home Repairs",
    defaultDescription:
      "Trusted plumber in Hinckley, Leicestershire. 24/7 emergency plumbing, boiler repair, blocked drains, and more. Vetted, Gas Safe plumbers. Call 0333 240 8428.",
    ogImage: "/og-image.jpg",
    twitterHandle: "",
  },

  // Geo prefix for multi-geo URL structure
  geoPrefix: "/plumber-hinckley",

  // Navigation
  nav: {
    main: [
      { label: "Home", href: "/" },
      { label: "Hinckley", href: "/plumber-hinckley" },
      { label: "Services", href: "/plumber-hinckley/services" },
      { label: "About", href: "/plumber-hinckley/about" },
      { label: "Contact", href: "/plumber-hinckley/contact" },
    ],
    cta: {
      label: "Call 0333 240 8428",
      href: "/plumber-hinckley/contact",
      phone: "tel:03332408428",
    },
  },
};

export type SEOConfig = typeof seoConfig;
